
ifdef CONFIG_VENDOR_SMARTISAN
obj-$(CONFIG_SND_REGMAP_SWR) += regmap-swr.o
else
obj-$(CONFIG_REGMAP_SWR) += regmap-swr.o
endif
obj-$(CONFIG_PINCTRL_WCD)	+= pinctrl-wcd.o
obj-$(CONFIG_PINCTRL_LPI)	+= pinctrl-lpi.o
obj-$(CONFIG_SOUNDWIRE)			+= soundwire.o
obj-$(CONFIG_SOUNDWIRE_WCD_CTRL)	+= swr-wcd-ctrl.o
